blank_issues_enabled: false
contact_links:
  - name: ❓ ¿Tenés preguntas?
    url: https://discord.com/invite/frontendcafe
    about: Si tenés preguntas o necesitas ayuda, podes ingresar a nuestro servidor de Discord FrontendCafé y buscar el canal '#jugueteando'!
