name: 💡 Feature Request
description: Sugerí una mejora.
title: "[Feat]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: Desde ya, gracias por tomarte el tiempo para completar esta solicitud. Nos gustaría mucho que trabajes en tu feature!

  - type: textarea
    id: feat-proposition
    attributes:
      label: ¿Qué te gustaría agregar a este proyecto?
      description: Por favor contanos brevemente qué es lo que consideras que falta o se podría mejorar?
      placeholder: No vemos la hora de saber de que se trata :)
    validations:
      required: true

  - type: textarea
    id: feat-description
    attributes:
      label: Descripción detallada.
      description: Describí de manera completa y técnica los requerimientos de la mejora y, si sabés, cómo implementarla.
      placeholder: |
        1. El texto en...
        2. Podría ser que...
        3. De color '#F3F3F3'.
    validations:
      required: true

  - type: checkboxes
    id: feat-agreement
    attributes:
      label: Código de conducta y licencia.
      options:
        - label: He comprobado que la feature solicitada no fue solicitada previamente.
          required: true
        - label: Estoy de acuerdo con seguir el [código de conducta](https://github.com/Juguetear/juguetear-web/blob/development/CODE_OF_CONDUCT.md) de este proyecto.
          required: true
        - label: Estoy de acuerdo con seguir las [licencias](https://github.com/Juguetear/juguetear-web/blob/development/CONTRIBUTING.md#licencias) de este proyecto.
          required: true
